export default [
  ['or', 'ores'],
  ['ón', 'ones'],
  ['al', 'ales'],
  ['il', 'iles'],
  ['el', 'eles'],
  ['er', 'eres'],
  ['ar', 'ares'],
  ['um', 'umes'],
  ['us', 'uses'],
  ['en', 'enes'],
  ['dén', 'denes'],
  ['és', 'eses'],
  ['án', 'anes'],
  ['ués', 'ueses'],
  ['ol', 'oles'],
  ['oy', 'oyes'],
  ['ós', 'oses'],
  ['ir', 'ires'],
  ['is', 'ises'],
  ['sh', 'shes'],
  ['tín', 'tines'],
  ['rín', 'rines'],
  ['lín', 'lines'],
  ['ry', 'ries'],
  ['iz', 'ices'],
  ['pás', 'pases'],
  ['aís', 'aíses'],
  ['oj', 'ojes'],
  ['bú', 'búes'],
  ['ch', 'ches'],
  ['lm', 'lmes'],
  // ['um', 'as'],
]