export default [
  // female nouns
  ['dad', 'dades'],
  ['eche', 'eches'],
  ['az', 'aces'],
  // ['ana', 'anos'],
  // ['stra', 'stros'],
  // ['ora', 'ores'],
  // ['gra', 'gros'],
  // ['oras', 'ores'],
  // ['rona', 'res'],
  // ['umna', 'umnos'],
  // ['ñola', 'ñoles'],
  // ['ñera', 'ñeros'],
  // ['gada', 'gados'],
  // ['aria', 'arios'],
  // ['jera', 'jeros'],
  // ['ueña', 'ueños'],

  // male nouns
  ['den', 'denes'],
  ['dén', 'denes'],
  ['ués', 'ueses'],
  ['tín', 'tines'],
  ['rín', 'rines'],
  ['lín', 'lines'],
  ['pás', 'pases'],
  ['aís', 'aíses'],
  ['or', 'ores'],
  ['ón', 'ones'],
  ['al', 'ales'],
  ['il', 'iles'],
  ['el', 'eles'],
  ['er', 'eres'],
  ['ar', 'ares'],
  ['um', 'umes'],
  ['us', 'uses'],
  ['en', 'enes'],
  ['és', 'eses'],
  ['án', 'anes'],
  ['ol', 'oles'],
  ['oy', 'oyes'],
  ['ós', 'oses'],
  ['ir', 'ires'],
  ['is', 'ises'],
  ['sh', 'shes'],
  ['ry', 'ries'],
  ['iz', 'ices'],
  ['oj', 'ojes'],
  ['bú', 'búes'],
  ['ch', 'ches'],
  ['lm', 'lmes'],

  // ['erra', 'erros'],
  // ['um', 'as'],
]