// generated in ./lib/models
export default {
  "presentTense": {
    "first": {
      "rules": "omenzar|2ienzo,raduar|3úo,spertar|2ierto,onfiar|3ío,ufrir|3o,ensar|ienso,omper|3o,orcer|uerzo,ormir|uermo,nviar|2ío,obernar|2ierno,uebrar|1iebro,uerer|1iero,gorar|1üero,isfacer|4go,trever|4o,oñar|ueño,contrar|1uentro,olgar|uelgo,jercer|3zo,aciar|2ío,enovar|2uevo,onfesar|3ieso,ruñir|3o,over|uevo,ehusar|2úso,aler|2go,ogar|uego,rohibir|3íbo,alir|2go,burrir|4o,orir|uero,oder|uedo,ntinuar|4úo,lmorzar|2uerzo,mpartir|5o,añer|2o,erder|ierdo,ravesar|3ieso,estir|isto,efender|2iendo,eber|2o,uiar|1ío,rrer|2o,pezar|1iezo,endar|iendo,tinguir|4o,meter|3o,cender|1iendo,hacer|2go,cordar|1uerdo,riar|1ío,eñir|iño,alentar|2iento,probar|2uebo,mitir|3o,eer|1o,mer|1o,vencer|3zo,vivir|3o,venir|3go,batir|3o,mostrar|1uestro,lir|1o,mir|1o,egir|ijo,edir|ido,reír|1ío,ostar|uesto,etir|ito,olver|uelvo,tender|1iendo,aer|1igo,decir|1igo,sistir|4o,tuar|1úo,brir|2o,entir|iento,vertir|1ierto,ger|jo,erir|iero,seguir|1igo,gir|jo,dir|1o,bir|1o,ducir|2zco,der|1o,uir|1yo,ner|1go,cer|zco,ar|o,omit|4o",
      "exceptions": "ir|voy,ser|1oy,negar|1iego,cerrar|1ierro,unir|2o,errar|yerro,servir|1irvo,jugar|2ego,sentar|1iento,oír|1igo,volar|1uelo,prever|5o,oler|huelo,caber|quepo,helar|1ielo,apretar|3ieto,dar|1oy,sonar|1ueno,regar|1iego,saber|1é,contar|1uento,estar|3oy,soler|1uelo,hervir|1iervo,ver|2o,beber|3o,torcer|1uerzo,querer|2iero,correr|4o,medir|1ido,leer|2o,temer|3o,elegir|2ijo,vender|4o,mover|1uevo,valer|3go,rogar|1uego,comer|3o,salir|3go,poder|1uedo,freír|2ío,tañer|3o,reír|1ío,deber|3o,abrir|3o,vestir|1isto",
      "rev": "omienzo|2enzar,rotejo|4ger,spierto|2ertar,ufro|3ir,ienso|ensar,ompo|3er,onrío|3eír,ierro|errar,arro|3er,uermo|ormir,errito|3etir,eriendo|2endar,obierno|2ernar,xijo|2gir,uiebro|1ebrar,güero|1orar,tisfago|5cer,irvo|ervir,ecido|4ir,trevo|4er,ueño|oñar,onsumo|5ir,ucedo|4er,cuentro|1ontrar,uelgo|olgar,acudo|4ir,jerzo|3cer,enuevo|2ovar,reo|2er,urjo|2gir,omito|4,ruño|3ir,ubo|2ir,ehúso|2usar,rohíbo|3ibir,burro|4ir,uero|orir,ambullo|6ir,injo|2gir,ielo|elar,lmuerzo|2orzar,prieto|2etar,omparto|6ir,flijo|3gir,ierdo|erder,ueno|onar,umplo|4ir,ñado|3ir,ependo|5er,irijo|3gir,nvado|4ir,fendo|4er,plaudo|5ir,omiendo|2endar,uento|ontar,iervo|ervir,iego|egar,primo|4ir,pido|1edir,piezo|1ezar,tingo|4uir,meto|3er,hago|2cer,cuerdo|1ordar,iño|eñir,aliento|2entar,ondo|3er,pruebo|2obar,veo|2r,mito|3ir,ieso|esar,venzo|3cer,vivo|3ir,vengo|3ir,bato|3ir,pito|1etir,muestro|1ostrar,rijo|1egir,cubro|4ir,prendo|5er,uesto|ostar,uelvo|olver,aigo|1er,digo|1ecir,sisto|4ir,cojo|2ger,iento|entir,vierto|1ertir,iero|erir,sigo|1eguir,ibo|2ir,úo|uar,duzco|2cir,iendo|ender,ío|iar,uyo|1ir,ngo|1er,zco|cer,o|ar,é|aber,stoy|2ar"
    },
    "second": {
      "rules": "omenzar|2ienzas,raduar|3úas,spertar|2iertas,onfiar|3ías,ufrir|3es,ensar|iensas,orcer|uerces,ormir|uermes,nviar|2ías,obernar|2iernas,uebrar|1iebras,uerer|1ieres,gorar|1üeras,oñar|ueñas,contrar|1uentras,olgar|uelgas,aciar|2ías,enovar|2uevas,onfesar|3iesas,ruñir|3es,over|ueves,ehusar|2úsas,ogar|uegas,rohibir|3íbes,burrir|4es,orir|ueres,oder|uedes,ntinuar|4úas,lmorzar|2uerzas,mpartir|5es,erder|ierdes,ravesar|3iesas,estir|istes,efender|2iendes,uiar|1ías,pezar|1iezas,endar|iendas,tinguir|5es,cender|1iendes,cordar|1uerdas,riar|1ías,eñir|iñes,alentar|2ientas,probar|2uebas,mitir|3es,vivir|3es,venir|1ienes,batir|3es,mostrar|1uestras,mir|1es,egir|iges,edir|ides,reír|1íes,ostar|uestas,etir|ites,olver|uelves,tender|1iendes,decir|1ices,sistir|4es,tuar|1úas,lir|1es,brir|2es,vertir|1iertes,erir|ieres,seguir|1igues,entir|ientes,gir|1es,dir|1es,bir|1es,ducir|3es,tener|1ienes,uir|1yes,r|s,omit|4as",
      "exceptions": "ir|vas,ser|eres,negar|1iegas,cerrar|1ierras,unir|2es,errar|yerras,servir|1irves,jugar|2egas,sentar|1ientas,oír|1yes,volar|1uelas,prever|4és,oler|hueles,helar|1ielas,apretar|3ietas,sonar|1uenas,regar|1iegas,contar|1uentas,estar|3ás,soler|1ueles,hervir|1ierves,querer|2ieres,elegir|2iges,rogar|1uegas,salir|3es,vestir|1istes",
      "rev": "mienzas|1enzar,piertas|1ertar,ufres|3ir,iensas|ensar,uerces|orcer,ierras|errar,uermes|ormir,biernas|1ernar,xiges|3ir,uiebras|1ebrar,güeras|1orar,irves|ervir,ecides|4ir,ueñas|oñar,uelas|olar,onsumes|5ir,uentras|ontrar,uelgas|olgar,revés|3er,enuevas|2ovar,urges|3ir,omitas|4,ruñes|3ir,ubes|2ir,ueves|over,ehúsas|2usar,rohíbes|3ibir,burres|4ir,ueres|orir,uedes|oder,mbulles|5ir,inges|3ir,ielas|elar,muerzas|1orzar,prietas|2etar,mpartes|5ir,fliges|4ir,ierdes|erder,uenas|onar,umples|4ir,iriges|4ir,uentas|ontar,stás|2ar,ierves|ervir,iegas|egar,primes|4ir,piezas|1ezar,iendas|endar,tingues|5ir,cuerdas|1ordar,uestras|ostrar,iñes|eñir,pruebas|2obar,udes|2ir,mites|3ir,iesas|esar,vives|3ir,vienes|1enir,bates|3ir,riges|1egir,ades|2ir,ides|edir,ríes|1eír,uestas|ostar,ites|etir,uelves|olver,ientas|entar,dices|1ecir,sistes|4ir,bres|2ir,viertes|1ertir,ieres|erir,sigues|1eguir,ibes|2ir,ientes|entir,úas|uar,duces|3ir,iendes|ender,tienes|1ener,ías|iar,uyes|1ir,s|r"
    },
    "third": {
      "rules": "omenzar|2ienza,raduar|3úa,spertar|2ierta,onfiar|3ía,ufrir|3e,ensar|iensa,orcer|uerce,ormir|uerme,nviar|2ía,obernar|2ierna,uebrar|1iebra,uerer|1iere,gorar|1üera,oñar|ueña,contrar|1uentra,olgar|uelga,aciar|2ía,enovar|2ueva,onfesar|3iesa,ruñir|3e,over|ueve,ehusar|2úsa,ogar|uega,rohibir|3íbe,burrir|4e,orir|uere,oder|uede,ntinuar|4úa,lmorzar|2uerza,mpartir|5e,erder|ierde,ravesar|3iesa,estir|iste,efender|2iende,uiar|1ía,pezar|1ieza,endar|ienda,tinguir|5e,cender|1iende,cordar|1uerda,riar|1ía,eñir|iñe,alentar|2ienta,probar|2ueba,mitir|3e,vivir|3e,venir|1iene,batir|3e,mostrar|1uestra,mir|1e,egir|ige,edir|ide,reír|1íe,ostar|uesta,etir|ite,olver|uelve,tender|1iende,decir|1ice,sistir|4e,tuar|1úa,lir|1e,brir|2e,vertir|1ierte,erir|iere,seguir|1igue,entir|iente,gir|1e,dir|1e,bir|1e,ducir|3e,tener|1iene,uir|1ye,r|,omit|4a",
      "exceptions": "ir|va,ser|es,negar|1iega,cerrar|1ierra,unir|2e,errar|yerra,servir|1irve,jugar|2ega,sentar|1ienta,oír|1ye,volar|1uela,prever|4é,oler|huele,helar|1iela,apretar|3ieta,sonar|1uena,regar|1iega,contar|1uenta,estar|3á,soler|1uele,hervir|1ierve,querer|2iere,elegir|2ige,valer|4,rogar|1uega,salir|3e,vestir|1iste,ver|2",
      "rev": "omienza|2enzar,spierta|2ertar,iensa|ensar,ierra|errar,obierna|2ernar,uiebra|1ebrar,güera|1orar,ueña|oñar,uela|olar,cuentra|1ontrar,uelga|olgar,enueva|2ovar,omita|4,ehúsa|2usar,iela|elar,lmuerza|2orzar,prieta|2etar,uena|onar,uenta|ontar,iega|egar,pieza|1ezar,ienda|endar,cuerda|1ordar,prueba|2obar,iesa|esar,muestra|1ostrar,uesta|ostar,ienta|entar,úa|uar,ía|iar,a|1r,rotege|6r,ufre|3ir,ompe|4r,uerce|orcer,uerme|ormir,xige|3ir,irve|ervir,ecide|4ir,treve|5r,onsume|5ir,ucede|5r,eme|3r,urge|3ir,ruñe|3ir,ube|2ir,ueve|over,rohíbe|3ibir,ome|3r,burre|4ir,uere|orir,uede|oder,ambulle|6ir,inge|3ir,omparte|6ir,añe|3r,flige|4ir,ierde|erder,umple|4ir,irige|4ir,ierve|ervir,ebe|3r,prime|4ir,rre|3r,tingue|5ir,mete|4r,iñe|eñir,ude|2ir,mite|3ir,ee|2r,vive|3ir,viene|1enir,bate|3ir,rige|1egir,abe|3r,ade|2ir,ide|edir,ríe|1eír,ite|etir,uelve|olver,ae|2r,dice|1ecir,siste|4ir,coge|4r,bre|2ir,vierte|1ertir,iere|erir,sigue|1eguir,ibe|2ir,iente|entir,pone|4r,duce|3ir,iende|ender,tiene|1ener,nde|3r,uye|1ir,ce|2r,revé|3er,stá|2ar"
    },
    "firstPlural": {
      "rules": "omit|4amos,r|mos",
      "exceptions": "ir|vamos,ser|1omos",
      "rev": "omos|er,mitamos|3,mos|r"
    },
    "secondPlural": {
      "rules": "omit|4áis,ír|1s,er|éis,ir|ís,ar|áis",
      "exceptions": "ir|vais,ser|1ois,dar|2is,ver|2is,oír|2s",
      "rev": "ois|er,omitáis|4,eis|1r,reís|3r,éis|er,ís|ir,áis|ar"
    },
    "thirdPlural": {
      "rules": "omenzar|2ienzan,raduar|3úan,spertar|2iertan,onfiar|3ían,ufrir|3en,ensar|iensan,orcer|uercen,ormir|uermen,nviar|2ían,obernar|2iernan,uebrar|1iebran,uerer|1ieren,gorar|1üeran,oñar|ueñan,contrar|1uentran,olgar|uelgan,aciar|2ían,enovar|2uevan,onfesar|3iesan,ruñir|3en,over|ueven,ehusar|2úsan,ogar|uegan,rohibir|3íben,burrir|4en,orir|ueren,oder|ueden,ntinuar|4úan,lmorzar|2uerzan,mpartir|5en,erder|ierden,ravesar|3iesan,estir|isten,efender|2ienden,uiar|1ían,pezar|1iezan,endar|iendan,tinguir|5en,cender|1ienden,cordar|1uerdan,riar|1ían,eñir|iñen,alentar|2ientan,probar|2ueban,mitir|3en,vivir|3en,venir|1ienen,batir|3en,mostrar|1uestran,mir|1en,egir|igen,edir|iden,reír|1íen,ostar|uestan,etir|iten,olver|uelven,tender|1ienden,decir|1icen,sistir|4en,tuar|1úan,lir|1en,brir|2en,vertir|1ierten,erir|ieren,seguir|1iguen,entir|ienten,gir|1en,dir|1en,bir|1en,ducir|3en,tener|1ienen,uir|1yen,r|n,omit|4an",
      "exceptions": "ir|van,ser|1on,negar|1iegan,cerrar|1ierran,unir|2en,errar|yerran,servir|1irven,jugar|2egan,sentar|1ientan,oír|1yen,volar|1uelan,prever|4én,oler|huelen,helar|1ielan,apretar|3ietan,sonar|1uenan,regar|1iegan,contar|1uentan,estar|3án,soler|1uelen,hervir|1ierven,querer|2ieren,elegir|2igen,rogar|1uegan,salir|3en,vestir|1isten",
      "rev": "mienzan|1enzar,on|er,piertan|1ertar,ufren|3ir,iensan|ensar,uercen|orcer,ierran|errar,uermen|ormir,biernan|1ernar,xigen|3ir,uiebran|1ebrar,güeran|1orar,irven|ervir,eciden|4ir,ueñan|oñar,uelan|olar,onsumen|5ir,uentran|ontrar,uelgan|olgar,revén|3er,enuevan|2ovar,urgen|3ir,omitan|4,ruñen|3ir,uben|2ir,ueven|over,ehúsan|2usar,rohíben|3ibir,burren|4ir,ueren|orir,ueden|oder,mbullen|5ir,ingen|3ir,ielan|elar,muerzan|1orzar,prietan|2etar,mparten|5ir,fligen|4ir,ierden|erder,uenan|onar,umplen|4ir,irigen|4ir,uentan|ontar,stán|2ar,ierven|ervir,iegan|egar,primen|4ir,piezan|1ezar,iendan|endar,tinguen|5ir,cuerdan|1ordar,uestran|ostrar,iñen|eñir,prueban|2obar,uden|2ir,miten|3ir,iesan|esar,viven|3ir,vienen|1enir,baten|3ir,rigen|1egir,aden|2ir,iden|edir,ríen|1eír,uestan|ostar,iten|etir,uelven|olver,ientan|entar,dicen|1ecir,sisten|4ir,bren|2ir,vierten|1ertir,ieren|erir,siguen|1eguir,iben|2ir,ienten|entir,úan|uar,ducen|3ir,ienden|ender,tienen|1ener,ían|iar,uyen|1ir,n|r"
    }
  },
  "pastTense": {
    "first": {
      "rules": "uerer|1ise,isfacer|3ice,eriguar|4üé,oder|ude,hacer|1ice,traer|3je,venir|1ine,aber|upe,decir|1ije,ír|1,poner|1use,ducir|2je,tener|1uve,gar|1ué,zar|cé,car|qué,er|í,ir|í,ar|é,ecarse|1qué,verse|1í,irse|í,arse|é,omit|4é",
      "exceptions": "ir|fui,andar|3uve,dar|1i,guiar|3e,estar|3uve,ver|1i,juntarse|4é,oír|2,prepararse|6é,prever|4í,mudarse|3é,leer|2í,creer|3í,hallarse|4é,valer|3í,sentirse|4í",
      "rev": "oví|2erse,rotegí|5er,ompí|3er,arrí|3er,orrí|3er,treví|4erse,ucedí|4er,emí|2er,repentí|6irse,omí|2er,ambullí|6irse,aí|1er,añí|2er,erdí|3er,ebí|2er,metí|3er,osí|2er,olí|2er,reí|3r,olví|3er,cogí|3er,ndí|2er,cí|1er,í|ir,nduve|2ar,uise|1erer,ude|oder,uie|2ar,stuve|2ar,traje|3er,vine|1enir,upe|aber,ice|acer,dije|1ecir,puse|1oner,duje|2cir,tuve|1ener,nteré|4arse,uedé|3arse,ronceé|5arse,equé|1carse,lamé|3arse,acté|3arse,omité|4,feité|4arse,verigüé|5uar,uejé|3arse,gué|1ar,cé|zar,qué|car,é|ar"
    },
    "second": {
      "rules": "uerer|1isiste,isfacer|3iciste,oder|udiste,hacer|1iciste,traer|3jiste,eer|1íste,venir|1iniste,aber|upiste,decir|1ijiste,poner|1usiste,ducir|2jiste,tener|1uviste,er|iste,r|ste,omit|4aste,verse|1iste,rse|ste",
      "exceptions": "ir|fuiste,andar|3uviste,caer|2íste,dar|1iste,estar|3uviste,atreverse|5iste,juntarse|5ste,prepararse|7ste,prever|4iste,mudarse|4ste,leer|2íste,creer|3íste,hallarse|5ste,valer|3iste,arrepentirse|9ste,poder|1udiste,sentirse|5ste,ver|1iste",
      "rev": "oviste|2erse,duviste|1ar,teraste|4rse,tegiste|3er,ompiste|3er,arriste|3er,uedaste|4rse,nceaste|4rse,uisiste|1erer,ecaste|3rse,orriste|3er,lamaste|4rse,cediste|3er,actaste|4rse,emiste|2er,mitaste|3,eitaste|4rse,omiste|2er,ulliste|4rse,uejaste|4rse,aíste|1er,añiste|2er,erdiste|3er,ebiste|2er,metiste|3er,rajiste|2er,osiste|2er,viniste|1enir,upiste|aber,oliste|2er,iciste|acer,olviste|3er,dijiste|1ecir,cogiste|3er,pusiste|1oner,dujiste|2cir,tuviste|1ener,ndiste|2er,ciste|1er,ste|r"
    },
    "third": {
      "rules": "ufrir|4ó,ormir|urmió,uerer|1iso,isfacer|3izo,ruñir|3ó,burrir|5ó,orir|urió,oder|udo,mpartir|6ó,añer|2ó,estir|istió,reír|1ió,tinguir|6ó,hacer|1izo,ervir|irvió,eñir|iñó,traer|3jo,mitir|4ó,eer|1yó,vivir|4ó,venir|1ino,batir|4ó,lir|2ó,aber|upo,entir|intió,mir|2ó,egir|igió,edir|idió,etir|itió,decir|1ijo,sistir|5ó,brir|3ó,vertir|1irtió,erir|irió,seguir|1iguió,gir|2ó,dir|2ó,poner|1uso,ducir|2jo,tener|1uvo,bir|2ó,uir|1yó,er|ió,ar|ó,omit|4ó,ullirse|3ó,verse|1ió,entirse|intió,arse|ó",
      "exceptions": "ir|fue,andar|3uvo,unir|3ó,criar|3o,oír|1yó,caer|2yó,dar|1io,guiar|3o,reír|1io,estar|3uvo,ver|1io,yacer|3ió,crecer|4ió,torcer|4ió,juntarse|4ó,prepararse|6ó,prever|4ió,mudarse|3ó,elegir|2igió,hallarse|4ó,salir|4ó,sentirse|1intió,freír|2ió,tañer|3ó,vestir|1istió",
      "rev": "ovió|2erse,loreció|5er,nteró|4arse,rotegió|5er,onteció|5er,ufrió|4r,ompió|3er,onrió|3eír,uedó|3arse,urmió|ormir,nió|2r,ronceó|5arse,xigió|4r,ecó|2arse,ecidió|5r,trevió|4erse,lamó|3arse,onsumió|6r,ucedió|4er,acudió|5r,jerció|4er,freció|4er,actó|3arse,emió|2er,urgió|4r,omitó|4,ruñó|3ir,feitó|4arse,epintió|2entirse,omió|2er,burrió|5r,urió|orir,vejeció|5er,ambulló|6irse,ingió|4r,uejó|3arse,ayó|1er,mpartió|6r,fligió|5r,erdió|3er,umplió|5r,irigió|5r,plaudió|6r,ereció|4er,ebió|2er,primió|5r,rrió|2er,leció|3er,tinguió|6r,metió|3er,irvió|ervir,iñó|eñir,queció|4er,mitió|4r,eyó|1er,osió|2er,nació|3er,venció|4er,vivió|4r,batió|4r,rigió|1egir,adió|3r,conoció|5er,intió|entir,idió|edir,itió|etir,olvió|3er,neció|3er,pareció|5er,sistió|5r,lió|1er,cogió|3er,brió|3r,virtió|1ertir,deció|3er,irió|erir,siguió|1eguir,bió|2r,uyó|1ir,ndió|2er,ó|ar,nduvo|2ar,uiso|1erer,udo|oder,uio|2ar,stuvo|2ar,trajo|3er,vino|1enir,upo|aber,izo|acer,dijo|1ecir,puso|1oner,dujo|2cir,tuvo|1ener"
    },
    "firstPlural": {
      "rules": "uerer|1isimos,isfacer|3icimos,oder|udimos,hacer|1icimos,traer|3jimos,eer|1ímos,venir|1inimos,aber|upimos,decir|1ijimos,poner|1usimos,ducir|2jimos,tener|1uvimos,er|imos,r|mos,omit|4amos,verse|1imos,rse|mos",
      "exceptions": "ir|fuimos,andar|3uvimos,caer|2ímos,dar|1imos,estar|3uvimos,atreverse|5imos,juntarse|5mos,prepararse|7mos,prever|4imos,mudarse|4mos,leer|2ímos,creer|3ímos,hallarse|5mos,valer|3imos,arrepentirse|9mos,poder|1udimos,sentirse|5mos,ver|1imos",
      "rev": "ovimos|2erse,duvimos|1ar,teramos|4rse,tegimos|3er,ompimos|3er,arrimos|3er,uedamos|4rse,nceamos|4rse,uisimos|1erer,ecamos|3rse,orrimos|3er,lamamos|4rse,cedimos|3er,actamos|4rse,emimos|2er,mitamos|3,eitamos|4rse,omimos|2er,ullimos|4rse,uejamos|4rse,aímos|1er,añimos|2er,erdimos|3er,ebimos|2er,metimos|3er,rajimos|2er,osimos|2er,vinimos|1enir,upimos|aber,olimos|2er,icimos|acer,olvimos|3er,dijimos|1ecir,cogimos|3er,pusimos|1oner,dujimos|2cir,tuvimos|1ener,ndimos|2er,cimos|1er,mos|r"
    },
    "secondPlural": {
      "rules": "uerer|1isisteis,isfacer|3icisteis,oder|udisteis,hacer|1icisteis,traer|3jisteis,eer|1ísteis,venir|1inisteis,aber|upisteis,decir|1ijisteis,poner|1usisteis,ducir|2jisteis,tener|1uvisteis,er|isteis,r|steis,omit|4asteis,verse|1isteis,rse|steis",
      "exceptions": "ir|fuisteis,andar|3uvisteis,caer|2ísteis,dar|1isteis,estar|3uvisteis,beber|3isteis,componer|4usisteis,moverse|3isteis,oponer|2usisteis,enterarse|6steis,proteger|6isteis,aprender|6isteis,romper|4isteis,barrer|4isteis,quedarse|5steis,broncearse|7steis,querer|2isisteis,prometer|6isteis,satisfacer|6icisteis,secarse|4steis,descender|7isteis,meter|3isteis,deshacer|4icisteis,resolver|6isteis,hacer|1icisteis,correr|4isteis,entretener|6uvisteis,atreverse|5isteis,extender|6isteis,juntarse|5steis,prepararse|7steis,llamarse|5steis,atraer|4jisteis,comprender|8isteis,suceder|5isteis,bendecir|4ijisteis,entender|6isteis,responder|7isteis,venir|1inisteis,encender|6isteis,prever|4isteis,oler|2isteis,mudarse|4steis,traer|3jisteis,leer|2ísteis,coser|3isteis,jactarse|5steis,temer|3isteis,creer|3ísteis,tener|1uvisteis,predecir|4ijisteis,vomit|5asteis,escoger|5isteis,coger|3isteis,proponer|4usisteis,vender|4isteis,convenir|4inisteis,hallarse|5steis,devolver|6isteis,valer|3isteis,afeitarse|6steis,suponer|3usisteis,arrepentirse|9steis,comer|3isteis,poner|1usisteis,esconder|6isteis,poder|1udisteis,caber|1upisteis,sorprender|8isteis,contener|4uvisteis,zambullirse|8steis,sentirse|5steis,toser|3isteis,quejarse|5steis,recoger|5isteis,detener|3uvisteis,tañer|3isteis,perder|4isteis,depender|6isteis,volver|4isteis,decir|1ijisteis,atender|5isteis,saber|1upisteis,deber|3isteis,obtener|3uvisteis,ofender|5isteis,soler|3isteis,defender|6isteis,mantener|4uvisteis,ver|1isteis,exponer|3usisteis",
      "rev": "aísteis|1er,jisteis|cir,cisteis|1er,steis|r"
    },
    "thirdPlural": {
      "rules": "ufrir|4eron,omper|3ieron,ormir|urmieron,uerer|1isieron,isfacer|3icieron,ruñir|3eron,burrir|5eron,orir|urieron,oder|udieron,mpartir|6eron,estir|istieron,eber|2ieron,rrer|2ieron,tinguir|6eron,meter|3ieron,hacer|1icieron,ervir|irvieron,eñir|iñeron,traer|3jeron,mitir|4eron,eer|1yeron,oser|2ieron,mer|1ieron,vivir|4eron,venir|1inieron,batir|4eron,lir|2eron,aber|upieron,entir|intieron,mir|2eron,egir|igieron,edir|idieron,reír|1ieron,etir|itieron,decir|1ijeron,sistir|5eron,ler|1ieron,brir|3eron,vertir|1irtieron,ger|1ieron,erir|irieron,seguir|1iguieron,gir|2eron,ver|1ieron,dir|2eron,poner|1usieron,ducir|2jeron,tener|1uvieron,bir|2eron,uir|1yeron,der|1ieron,cer|1ieron,r|1on,omit|4aron,ullirse|3eron,verse|1ieron,entirse|intieron,arse|2on",
      "exceptions": "ir|fueron,andar|3uvieron,unir|3eron,oír|1yeron,caer|2yeron,dar|1ieron,estar|3uvieron,consentir|4intieron,divertir|3irtieron,presentir|4intieron,regir|1igieron,sufrir|5eron,dormir|1urmieron,exigir|5eron,extinguir|8eron,advertir|3irtieron,servir|1irvieron,decidir|6eron,atreverse|5ieron,juntarse|6on,prepararse|8on,conseguir|4iguieron,convertir|4irtieron,prever|4ieron,admitir|6eron,mudarse|5on,elegir|2igieron,perseguir|4iguieron,hallarse|6on,corregir|4igieron,arrepentirse|5intieron,salir|4eron,aburrir|6eron,permitir|7eron,poder|1udieron,distinguir|9eron,sentirse|1intieron,freír|2ieron,compartir|8eron,seguir|1iguieron,afligir|6eron,mentir|1intieron,invertir|3irtieron,dirigir|6eron,reír|1ieron,vestir|1istieron,hervir|1irvieron,ver|1ieron,proseguir|4iguieron",
      "rev": "ovieron|2erse,teraron|5se,egieron|2er,mpieron|2er,nrieron|2eír,uedaron|5se,ncearon|5se,isieron|erer,ecaron|4se,lamaron|5se,umieron|3r,actaron|5se,emieron|2er,rgieron|3r,mitaron|3,ruñeron|3ir,eitaron|5se,omieron|2er,urieron|orir,ulleron|3irse,ngieron|3r,uejaron|5se,ayeron|1er,plieron|3r,ebieron|2er,imieron|3r,rrieron|2er,etieron|2er,ivieron|3r,iñeron|eñir,rajeron|2er,udieron|3r,inieron|enir,eyeron|1er,osieron|2er,atieron|3r,upieron|aber,adieron|3r,idieron|edir,itieron|etir,icieron|acer,lvieron|2er,dijeron|1ecir,stieron|3r,lieron|1er,ogieron|2er,brieron|3r,irieron|erir,usieron|oner,dujeron|2cir,uvieron|ener,bieron|2r,uyeron|1ir,dieron|1er,cieron|1er,ron|1"
    }
  },
  "futureTense": {
    "first": {
      "rules": "uerer|3ré,isfacer|4ré,aler|2dré,alir|2dré,oder|2ré,hacer|2ré,venir|3dré,aber|2ré,ír|iré,ner|1dré,r|1é,omit|4aré,rse|1é",
      "exceptions": "decir|1iré,hacer|2ré,juntarse|6é,oír|1iré,prepararse|8é,mudarse|5é,hallarse|6é,salir|3dré,sentirse|6é",
      "rev": "overé|4se,nteraré|6se,uedaré|5se,oncearé|6se,uerré|3er,tisfaré|5cer,ecaré|4se,esharé|4cer,treveré|6se,lamaré|5se,actaré|5se,omitaré|4,feitaré|6se,pentiré|6se,odré|2er,bulliré|6se,uejaré|5se,vendré|3ir,abré|2er,reiré|2ír,dré|er,ré|1"
    },
    "second": {
      "rules": "uerer|3rás,isfacer|4rás,aler|2drás,alir|2drás,oder|2rás,hacer|2rás,venir|3drás,aber|2rás,ír|irás,ner|1drás,r|1ás,omit|4arás,rse|1ás",
      "exceptions": "decir|1irás,hacer|2rás,atreverse|7ás,juntarse|6ás,oír|1irás,prepararse|8ás,mudarse|5ás,hallarse|6ás,arrepentirse|10ás,salir|3drás,sentirse|6ás",
      "rev": "overás|4se,terarás|5se,uedarás|5se,ncearás|5se,uerrás|3er,isfarás|4cer,ecarás|4se,esharás|4cer,lamarás|5se,actarás|5se,mitarás|3,eitarás|5se,odrás|2er,ullirás|5se,uejarás|5se,vendrás|3ir,abrás|2er,reirás|2ír,drás|er,rás|1"
    },
    "third": {
      "rules": "uerer|3rá,isfacer|4rá,aler|2drá,alir|2drá,oder|2rá,hacer|2rá,venir|3drá,aber|2rá,ír|irá,ner|1drá,r|1á,omit|4ará,rse|1á",
      "exceptions": "decir|1irá,hacer|2rá,juntarse|6á,oír|1irá,prepararse|8á,mudarse|5á,hallarse|6á,salir|3drá,sentirse|6á",
      "rev": "overá|4se,nterará|6se,uedará|5se,onceará|6se,uerrá|3er,tisfará|5cer,ecará|4se,eshará|4cer,treverá|6se,lamará|5se,actará|5se,omitará|4,feitará|6se,pentirá|6se,odrá|2er,bullirá|6se,uejará|5se,vendrá|3ir,abrá|2er,reirá|2ír,drá|er,rá|1"
    },
    "firstPlural": {
      "rules": "uerer|3remos,isfacer|4remos,aler|2dremos,alir|2dremos,oder|2remos,hacer|2remos,venir|3dremos,aber|2remos,ír|iremos,ner|1dremos,r|1emos,omit|4aremos,rse|1emos",
      "exceptions": "decir|1iremos,moverse|5emos,enterarse|7emos,quedarse|6emos,broncearse|8emos,satisfacer|7remos,secarse|5emos,deshacer|5remos,hacer|2remos,atreverse|7emos,juntarse|6emos,oír|1iremos,prepararse|8emos,llamarse|6emos,venir|3dremos,mudarse|5emos,jactarse|6emos,vomit|5aremos,convenir|6dremos,hallarse|6emos,afeitarse|7emos,arrepentirse|10emos,salir|3dremos,zambullirse|9emos,sentirse|6emos,quejarse|6emos",
      "rev": "erremos|2er,odremos|2er,abremos|2er,eiremos|1ír,dremos|er,remos|1"
    },
    "secondPlural": {
      "rules": "uerer|3réis,isfacer|4réis,aler|2dréis,alir|2dréis,oder|2réis,hacer|2réis,venir|3dréis,aber|2réis,ír|iréis,ner|1dréis,r|1éis,omit|4aréis,rse|1éis",
      "exceptions": "decir|1iréis,enterarse|7éis,quedarse|6éis,broncearse|8éis,hacer|2réis,atreverse|7éis,juntarse|6éis,oír|1iréis,prepararse|8éis,llamarse|6éis,venir|3dréis,mudarse|5éis,vomit|5aréis,convenir|6dréis,hallarse|6éis,afeitarse|7éis,arrepentirse|10éis,salir|3dréis,sentirse|6éis,quejarse|6éis",
      "rev": "overéis|4se,uerréis|3er,sfaréis|3cer,ecaréis|4se,sharéis|3cer,ctaréis|4se,odréis|2er,lliréis|4se,abréis|2er,reiréis|2ír,dréis|er,réis|1"
    },
    "thirdPlural": {
      "rules": "uerer|3rán,isfacer|4rán,aler|2drán,alir|2drán,oder|2rán,hacer|2rán,venir|3drán,aber|2rán,ír|irán,ner|1drán,r|1án,omit|4arán,rse|1án",
      "exceptions": "decir|1irán,hacer|2rán,atreverse|7án,juntarse|6án,oír|1irán,prepararse|8án,mudarse|5án,hallarse|6án,arrepentirse|10án,salir|3drán,sentirse|6án",
      "rev": "overán|4se,terarán|5se,uedarán|5se,ncearán|5se,uerrán|3er,isfarán|4cer,ecarán|4se,esharán|4cer,lamarán|5se,actarán|5se,mitarán|3,eitarán|5se,odrán|2er,ullirán|5se,uejarán|5se,vendrán|3ir,abrán|2er,reirán|2ír,drán|er,rán|1"
    }
  },
  "conditional": {
    "first": {
      "rules": "uerer|3ría,isfacer|4ría,aler|2dría,alir|2dría,oder|2ría,hacer|2ría,venir|3dría,aber|2ría,ír|iría,ner|1dría,r|1ía,omit|4aría,rse|1ía",
      "exceptions": "decir|1iría,hacer|2ría,atreverse|7ía,juntarse|6ía,oír|1iría,prepararse|8ía,mudarse|5ía,hallarse|6ía,arrepentirse|10ía,salir|3dría,sentirse|6ía",
      "rev": "overía|4se,teraría|5se,uedaría|5se,ncearía|5se,uerría|3er,isfaría|4cer,ecaría|4se,esharía|4cer,lamaría|5se,actaría|5se,mitaría|3,eitaría|5se,odría|2er,ulliría|5se,uejaría|5se,vendría|3ir,abría|2er,reiría|2ír,dría|er,ría|1"
    },
    "second": {
      "rules": "uerer|3rías,isfacer|4rías,aler|2drías,alir|2drías,oder|2rías,hacer|2rías,venir|3drías,aber|2rías,ír|irías,ner|1drías,r|1ías,omit|4arías,rse|1ías",
      "exceptions": "decir|1irías,enterarse|7ías,quedarse|6ías,broncearse|8ías,hacer|2rías,atreverse|7ías,juntarse|6ías,oír|1irías,prepararse|8ías,llamarse|6ías,venir|3drías,mudarse|5ías,vomit|5arías,convenir|6drías,hallarse|6ías,afeitarse|7ías,arrepentirse|10ías,salir|3drías,sentirse|6ías,quejarse|6ías",
      "rev": "overías|4se,uerrías|3er,sfarías|3cer,ecarías|4se,sharías|3cer,ctarías|4se,odrías|2er,llirías|4se,abrías|2er,reirías|2ír,drías|er,rías|1"
    },
    "third": {
      "rules": "uerer|3ría,isfacer|4ría,aler|2dría,alir|2dría,oder|2ría,hacer|2ría,venir|3dría,aber|2ría,ír|iría,ner|1dría,r|1ía,omit|4aría,rse|1ía",
      "exceptions": "decir|1iría,hacer|2ría,atreverse|7ía,juntarse|6ía,oír|1iría,prepararse|8ía,mudarse|5ía,hallarse|6ía,arrepentirse|10ía,salir|3dría,sentirse|6ía",
      "rev": "overía|4se,teraría|5se,uedaría|5se,ncearía|5se,uerría|3er,isfaría|4cer,ecaría|4se,esharía|4cer,lamaría|5se,actaría|5se,mitaría|3,eitaría|5se,odría|2er,ulliría|5se,uejaría|5se,vendría|3ir,abría|2er,reiría|2ír,dría|er,ría|1"
    },
    "firstPlural": {
      "rules": "uerer|3ríamos,isfacer|4ríamos,aler|2dríamos,alir|2dríamos,oder|2ríamos,hacer|2ríamos,venir|3dríamos,aber|2ríamos,ír|iríamos,ner|1dríamos,r|1íamos,omit|4aríamos,rse|1íamos",
      "exceptions": "decir|1iríamos,moverse|5íamos,enterarse|7íamos,sonreír|5iríamos,quedarse|6íamos,broncearse|8íamos,satisfacer|7ríamos,secarse|5íamos,deshacer|5ríamos,hacer|2ríamos,atreverse|7íamos,juntarse|6íamos,oír|1iríamos,prepararse|8íamos,llamarse|6íamos,venir|3dríamos,mudarse|5íamos,jactarse|6íamos,vomit|5aríamos,convenir|6dríamos,hallarse|6íamos,afeitarse|7íamos,arrepentirse|10íamos,salir|3dríamos,poder|3ríamos,zambullirse|9íamos,sentirse|6íamos,freír|3iríamos,quejarse|6íamos,reír|2iríamos",
      "rev": "rríamos|1er,bríamos|1er,dríamos|er,ríamos|1"
    },
    "secondPlural": {
      "rules": "uerer|3ríais,isfacer|4ríais,aler|2dríais,alir|2dríais,oder|2ríais,hacer|2ríais,venir|3dríais,aber|2ríais,ír|iríais,ner|1dríais,r|1íais,omit|4aríais,rse|1íais",
      "exceptions": "decir|1iríais,moverse|5íais,enterarse|7íais,quedarse|6íais,broncearse|8íais,satisfacer|7ríais,secarse|5íais,deshacer|5ríais,hacer|2ríais,atreverse|7íais,juntarse|6íais,oír|1iríais,prepararse|8íais,llamarse|6íais,venir|3dríais,mudarse|5íais,jactarse|6íais,vomit|5aríais,convenir|6dríais,hallarse|6íais,afeitarse|7íais,arrepentirse|10íais,salir|3dríais,zambullirse|9íais,sentirse|6íais,quejarse|6íais",
      "rev": "erríais|2er,odríais|2er,abríais|2er,eiríais|1ír,dríais|er,ríais|1"
    },
    "thirdPlural": {
      "rules": "uerer|3rían,isfacer|4rían,aler|2drían,alir|2drían,oder|2rían,hacer|2rían,venir|3drían,aber|2rían,ír|irían,ner|1drían,r|1ían,omit|4arían,rse|1ían",
      "exceptions": "decir|1irían,enterarse|7ían,quedarse|6ían,broncearse|8ían,hacer|2rían,atreverse|7ían,juntarse|6ían,oír|1irían,prepararse|8ían,llamarse|6ían,venir|3drían,mudarse|5ían,vomit|5arían,convenir|6drían,hallarse|6ían,afeitarse|7ían,arrepentirse|10ían,salir|3drían,sentirse|6ían,quejarse|6ían",
      "rev": "overían|4se,uerrían|3er,sfarían|3cer,ecarían|4se,sharían|3cer,ctarían|4se,odrían|2er,llirían|4se,abrían|2er,reirían|2ír,drían|er,rían|1"
    }
  },
  "gerunds": {
    "gerunds": {
      "rules": "omper|3iendo,ormir|urmiendo,oncebir|3ibiendo,orir|uriendo,odrir|udriendo,oer|1yendo,ejer|2iendo,endir|indiendo,rgüir|2uyendo,ngullir|5endo,ervir|irviendo,oser|2iendo,minuir|4yendo,huir|2yendo,oír|1yendo,mer|1iendo,egir|igiendo,etir|itiendo,estir|istiendo,eñir|iñendo,reír|1iendo,ler|1iendo,pedir|1idiendo,struir|4yendo,eer|1yendo,seguir|1iguiendo,entir|intiendo,buir|2yendo,rer|1iendo,decir|1iciendo,luir|2yendo,vertir|1irtiendo,ter|1iendo,venir|1iniendo,ber|1iendo,stituir|5yendo,ger|1iendo,aer|1yendo,erir|iriendo,ver|1iendo,ner|1iendo,der|1iendo,cer|1iendo,ir|1endo,r|ndo",
      "exceptions": "ir|yendo,poder|1udiendo,medir|1idiendo,seguir|1iguiendo,servir|1irviendo,convertir|4irtiendo,elegir|2igiendo,conseguir|4iguiendo,romper|4iendo,repetir|3itiendo,adquirir|7endo,sufrir|5endo,correr|4iendo,recorrer|6iendo,reír|1iendo,pedir|1idiendo,valer|3iendo,dormir|1urmiendo,concebir|4ibiendo,impedir|3idiendo,derretir|4itiendo,barrer|4iendo,vestir|1istiendo,sentir|1intiendo,hundir|5endo,mentir|1intiendo,extinguir|8endo,distinguir|9endo,podrir|1udriendo,verter|4iendo,expandir|7endo,invertir|3irtiendo,esparcir|7endo,roer|2yendo,difundir|7endo,perseguir|4iguiendo,definir|6endo,converger|7iendo,emerger|5iendo,revertir|3irtiendo,hervir|1irviendo,despedir|4idiendo,confundir|8endo,moler|3iendo,transgredir|10endo,corregir|4igiendo,proseguir|4iguiendo,demoler|5iendo,regir|1igiendo,fundir|5endo,reseguir|3iguiendo,advertir|3irtiendo,rendir|1indiendo,redefinir|8endo,freír|2iendo,competir|4itiendo,prescindir|9endo,desmentir|4intiendo,consentir|4intiendo,embestir|3istiendo,refundir|7endo,expedir|3idiendo,reconvertir|6irtiendo,revestir|3istiendo,infundir|7endo,blandir|6endo,divertir|3irtiendo,inquirir|7endo,fruncir|6endo,pervertir|4irtiendo,descorrer|7iendo,asir|3endo,presentir|4intiendo,escindir|7endo",
      "rev": "emiendo|2er,omiendo|2er,uriendo|orir,egiendo|2er,rniendo|3r,eliendo|2er,amiendo|2er,ejiendo|2er,triendo|3r,guyendo|1üir,ullendo|3ir,quiendo|3r,nriendo|2eír,eriendo|2er,osiendo|2er,ebiendo|2er,uniendo|3r,oyendo|1ír,abiendo|2er,rbiendo|2er,piendo|2r,iñendo|eñir,adiendo|3r,eyendo|1er,iviendo|3r,udiendo|3r,ogiendo|2er,iciendo|ecir,rriendo|3r,etiendo|2er,liendo|2r,briendo|3r,idiendo|3r,iniendo|enir,ayendo|1er,iriendo|erir,uciendo|3r,giendo|2r,viendo|1er,biendo|2r,miendo|2r,yendo|ir,niendo|1er,tiendo|2r,diendo|1er,ciendo|1er,ndo|r"
    }
  }
}