const rb = 'Adverb'
const nn = 'Noun'
const vb = 'Verb'
const jj = 'Adjective'
const cond = 'Conditional'
const fut = 'FutureTense'
// const inf = 'Infinitive'
const g = 'Gerund'
const ref = 'Reflexive'
const first = 'FirstPerson'

export default [
  null,
  {
    // one-letter suffixes
    'ó': vb,
  },
  {
    // two-letter suffixes
    al: jj,
    ño: jj,
    // no: jj,
    // do: vb,
    // ar: vb,
    an: vb,
    'ió': vb,
    en: vb,
    ir: vb,
    er: vb,
    'tó': vb,
  },
  {
    // three-letter suffixes
    ico: jj,
    // ica: jj,
    ble: jj,
    nal: jj,
    ial: jj,
    oso: jj,
    iso: jj,
    ito: jj,
    ita: jj,
    izo: jj,
    cto: jj,
    ana: jj,
    eos: jj,
    // ado: vb,
    ndo: first,
    ada: vb,
    ron: vb,
    // ido: vb,
    aba: vb,
    tar: vb,
    gar: vb,
    nar: vb,
    'ían': vb,
    rar: vb,
    ría: cond,
    aré: fut,
    iré: fut,
    eré: fut,
    rás: fut,
    ará: fut,
    ado: vb,
    pto: jj,
    osa: jj,
    tos: jj,

    // ida: vb,
  },
  {
    // four-letter suffixes
    itas: jj,
    itos: jj,
    icos: jj,
    icas: jj,
    tico: jj,
    fica: jj,
    gica: jj,
    mica: jj,
    nica: jj,
    lica: jj,
    tica: jj,
    able: jj,
    tivo: jj,
    sivo: jj,
    esco: jj,
    iaco: jj,
    íaco: jj,
    áceo: jj,
    áneo: jj,
    icio: jj,
    culo: jj,
    aria: jj,
    bles: jj,
    tiva: jj,
    ante: jj,
    ente: jj,
    ánea: jj,
    siva: jj,
    ular: jj,
    osas: jj,
    ales: jj,
    iles: jj,
    anos: jj,
    osos: jj,
    'ción': nn,
    idad: nn,
    ento: nn,
    ncia: nn,
    'sión': nn,
    ando: g,
    endo: g,
    // ados: vb,
    aron: vb,
    adas: vb,
    tado: first,
    rías: cond,
    amos: cond,
    íais: cond,
    rían: cond,
    réis: fut,
    arán: fut,
    // refexive verbs
    arse: ref,
    arte: ref,
    arme: ref,
    irse: ref,
    irte: ref,
    erse: ref,
    dose: ref,
    ario: jj,
    orio: jj,
    iano: jj,
    dero: jj,
    fero: jj,
    jero: jj,
    lero: jj,
    nero: jj,
    tero: jj,
    ares: jj,
    ores: jj,
    rios: jj,
    ivos: jj,
  },
  { // five-letter suffixes
    'ación': nn,
    mente: rb,
    ísimo: jj,
    icano: jj,
    ntino: jj,
    tivas: jj,
    andés: jj,
    adora: jj,
    antes: jj,
    iendo: g,
    yendo: g,
    ieron: vb,
    remos: fut,
    iente: jj,
    entes: jj,
  },
  {
    // six-letter suffixes
    ística: jj,
    ciones: nn,
  },
  {
    // seven-letter suffixes
    aciones: nn
  }
]